# Copyright (c) 2023 HabanaLabs, Ltd.
#
# SPDX-License-Identifier: Apache-2.0
#
# HabanaLabs Dockerfile base installer layer for Ubuntu 22.04
FROM ubuntu:jammy
ARG ARTIFACTORY_URL
ARG VERSION
ARG REVISION

ENV DEBIAN_FRONTEND=noninteractive
ENV GC_KERNEL_PATH=/usr/lib/habanalabs/libtpc_kernels.so:/usr/lib/habanalabs/libtpc_scalar_kernels.so
ENV HABANA_LOGS=/var/log/habana_logs/
ENV OS_NUMBER=2204
ENV HABANA_SCAL_BIN_PATH=/opt/habanalabs/engines_fw
ENV HABANA_PLUGINS_LIB_PATH=/opt/habanalabs/habana_plugins

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    apt-transport-https \
    apt-utils \
    bc \
    build-essential \
    ca-certificates \
    dkms \
    ethtool \
    gcc \
    git \
    gnupg \
    gpg-agent \
    graphviz \
    libgl1 \
    libgoogle-glog0v5 \
    libjemalloc2 \
    libpq-dev \
    locales \
    lsof \
    make \
    openssh-client \
    openssh-server \
    protobuf-compiler \
    python3 \
    python3-dev \
    python3-pip \
    python3-tk \
    python3-venv \
    unzip \
    vim \
    wget && \
    apt-get autoremove && apt-get clean

RUN locale-gen en_US.UTF-8

ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8
ENV LC_CTYPE=en_US.UTF-8

# There is no need to store pip installation files inside docker image
ENV PIP_NO_CACHE_DIR=on
ENV PIP_DISABLE_PIP_VERSION_CHECK=1

RUN python3 -m pip install pip==22.2.2 setuptools==67.3.3 wheel==0.38.4

COPY install_efa.sh .
RUN ./install_efa.sh && rm install_efa.sh

ENV MPI_ROOT=/opt/amazon/openmpi
ENV LD_LIBRARY_PATH=${MPI_ROOT}/lib:/opt/amazon/efa/lib:/usr/lib/habanalabs:$LD_LIBRARY_PATH
ENV PATH=${MPI_ROOT}/bin:/opt/amazon/efa/bin:$PATH
ENV OPAL_PREFIX=${MPI_ROOT}
ENV MPICC=${MPI_ROOT}/bin/mpicc
ENV RDMAV_FORK_SAFE=1
ENV FI_EFA_USE_DEVICE_RDMA=1
ENV RDMA_CORE_ROOT=/opt/habanalabs/rdma-core/src
ENV RDMA_CORE_LIB=${RDMA_CORE_ROOT}/build/lib

RUN wget -O- https://${ARTIFACTORY_URL}/artifactory/api/gpg/key/public | gpg --dearmor -o /usr/share/keyrings/habana-artifactory.gpg && \
    chown root:root /usr/share/keyrings/habana-artifactory.gpg && \
    chmod 644 /usr/share/keyrings/habana-artifactory.gpg  && \
    echo "deb [signed-by=/usr/share/keyrings/habana-artifactory.gpg] https://${ARTIFACTORY_URL}/artifactory/debian jammy main" | tee -a /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y habanalabs-rdma-core="$VERSION"-"$REVISION" \
        habanalabs-thunk="$VERSION"-"$REVISION" \
        habanalabs-firmware-tools="$VERSION"-"$REVISION" \
        habanalabs-graph="$VERSION"-"$REVISION" && \
    apt-get autoremove --yes && apt-get clean && rm -rf /var/lib/apt/lists/* && \
    sed --in-place "/$ARTIFACTORY_URL/d" /etc/apt/sources.list

RUN python3 -m pip install habana_media_loader=="${VERSION}"."${REVISION}"

# SSH configuration necessary to support mpi-operator v2
RUN mkdir -p /var/run/sshd && \
    sed -i 's/[ #]\(.*StrictHostKeyChecking \).*/ \1no/g' /etc/ssh/ssh_config && \
    sed -i 's/#\(ForwardAgent \).*/\1yes/g' /etc/ssh/ssh_config && \
    echo "    UserKnownHostsFile /dev/null" >> /etc/ssh/ssh_config && \
    sed -i 's/#\(StrictModes \).*/\1no/g' /etc/ssh/sshd_config && \
    echo "/etc/init.d/ssh start \"-p 3022\"" >> ~/.bashrc && \
    sed -i '/[ -z "$PS1" ] && return/s/^/#/g' ~/.bashrc