# Copyright (c) 2024 Habana Labs, Ltd.
#
# SPDX-License-Identifier: Apache-2.0
#
# HabanaLabs Dockerfile base installer layer for SUSE 15.5
FROM registry.suse.com/suse/sle15:15.5
ARG ARTIFACTORY_URL
ARG VERSION
ARG REVISION

# for RHEL certification
LABEL vendor="Habanalabs Ltd."
LABEL release="${VERSION}-${REVISION}"

COPY LICENSE /licenses/

RUN zypper addrepo -f http://download.opensuse.org/distribution/leap/15.5/repo/oss/ OpenSUSI && \
    echo "gpgcheck=0" >> /etc/zypp/repos.d/OpenSUSI.repo && \
    echo "repo_gpgcheck=0" >> /etc/zypp/repos.d/OpenSUSI.repo

RUN zypper addrepo -f http://download.opensuse.org/source/distribution/leap/15.5/repo/oss/ OpenSUSISrc && \
    echo "gpgcheck=0" >> /etc/zypp/repos.d/OpenSUSISrc.repo && \
    echo "repo_gpgcheck=0" >> /etc/zypp/repos.d/OpenSUSISrc.repo

RUN zypper refresh && \
    zypper install -y kernel-devel-5.14.21-150500.55.94.1 kernel-macros-5.14.21-150500.55.94.1  && \
    zypper update -y && \
    zypper clean

RUN zypper update -y && zypper install -y --allow-downgrade \
        clang \
        cmake \
        ffmpeg \
        gcc \
        gcc-c++ \
        git \
        glibc-devel \
        iproute \
        jemalloc \
        lbzip2 \
        libarchive-devel \
        libffi-devel \
        libjpeg-devel \
        libksba \
        linux-glibc-devel \
        llvm \
        lsof \
        Mesa-libGL-devel \
        Mesa-libGL1 \
        openssh-clients \
        openssh-server \
        openssl \
        openssl-devel \
        python311 \
        python311-devel \
        python311-pip \
        unzip \
        wget \
        zlib-devel && \
    zypper clean && \
    rm -f /etc/ssh/ssh_host_*_key*

ENV PIP_DISABLE_PIP_VERSION_CHECK=1
ENV PIP_NO_CACHE_DIR=on

RUN alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 2 && \
    alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 1 && \
    alternatives --set python3 /usr/bin/python3.11

RUN python3 -m pip install setuptools==75.1.0 wheel==0.44.0

COPY install_efa.sh .
RUN ./install_efa.sh && rm -f install_efa.sh /etc/ld.so.conf.d/efa.conf /etc/profile.d/efa.sh

ENV LIBFABRIC_VERSION="1.22.0"
ENV LIBFABRIC_ROOT="/opt/habanalabs/libfabric-${LIBFABRIC_VERSION}"
ENV MPI_ROOT=/opt/amazon/openmpi
ENV LD_LIBRARY_PATH=$LIBFABRIC_ROOT/lib:${MPI_ROOT}/lib:/usr/lib/habanalabs:$LD_LIBRARY_PATH
ENV PATH=${LIBFABRIC_ROOT}/bin:${MPI_ROOT}/bin:$PATH
ENV OPAL_PREFIX=${MPI_ROOT}
ENV MPICC=${MPI_ROOT}/bin/mpicc
ENV RDMA_FORK_SAFE=1
ENV FI_EFA_USE_DEVICE_RDMA=1

RUN echo "[habanalabs]" > /etc/zypp/repos.d/habanalabs.repo && \
    echo "name=Habana SUSE Linux repo" >> /etc/zypp/repos.d/habanalabs.repo && \
    echo "baseurl=https://${ARTIFACTORY_URL}/artifactory/sles/15/15.5" >> /etc/zypp/repos.d/habanalabs.repo && \
    echo "gpgkey=https://${ARTIFACTORY_URL}/artifactory/sles/15/15.5/repodata/repomd.xml.key" >> /etc/zypp/repos.d/habanalabs.repo && \
    echo "gpgcheck=1" >> /etc/zypp/repos.d/habanalabs.repo

RUN zypper --gpg-auto-import-keys install -y \
        habanalabs-rdma-core-"$VERSION"-"$REVISION" \
        habanalabs-thunk-"$VERSION"-"$REVISION" \
        habanalabs-firmware-tools-"$VERSION"-"$REVISION" \
        habanalabs-graph-"$VERSION"-"$REVISION" && \
    zypper clean && \
    rm -f /etc/zypp/repos.d/habanalabs.repo

ENV RDMA_CORE_ROOT=/opt/habanalabs/rdma-core/src
ENV RDMA_CORE_LIB=${RDMA_CORE_ROOT}/build/lib

RUN wget -nv -O /tmp/libfabric-${LIBFABRIC_VERSION}.tar.bz2 https://github.com/ofiwg/libfabric/releases/download/v${LIBFABRIC_VERSION}/libfabric-${LIBFABRIC_VERSION}.tar.bz2 && \
    cd /tmp/ && tar xf /tmp/libfabric-${LIBFABRIC_VERSION}.tar.bz2 && \
    cd /tmp/libfabric-${LIBFABRIC_VERSION} && \
    ./configure --prefix=$LIBFABRIC_ROOT --enable-psm3-verbs --enable-verbs=yes --with-synapseai=/usr && \
    make && make install && cd / && rm -rf /tmp/libfabric-${LIBFABRIC_VERSION}.tar.bz2 /tmp/libfabric-${LIBFABRIC_VERSION}

RUN wget -nv -O /tmp/main.zip https://github.com/HabanaAI/hccl_ofi_wrapper/archive/refs/heads/main.zip && \
    unzip /tmp/main.zip -d /tmp && \
    cd /tmp/hccl_ofi_wrapper-main && \
    make && cp -f libhccl_ofi_wrapper.so /usr/lib/habanalabs/libhccl_ofi_wrapper.so && \
    cd / && \
    rm -rf /tmp/main.zip /tmp/hccl_ofi_wrapper-main

RUN python3 -m pip install habana_media_loader=="${VERSION}"."${REVISION}"

# SSH configuration necessary to support mpi-operator v2
RUN mkdir -p /var/run/sshd && \
    sed -i 's/[ #]\(.*StrictHostKeyChecking \).*/ \1no/g' /etc/ssh/ssh_config && \
    sed -i 's/#\(ForwardAgent \).*/\1yes/g' /etc/ssh/ssh_config && \
    echo "    UserKnownHostsFile /dev/null" >> /etc/ssh/ssh_config && \
    sed -i 's/#\(StrictModes \).*/\1no/g' /etc/ssh/sshd_config && \
    mkdir -p /var/run/sshd && echo "/usr/sbin/sshd -p 3022" | tee -a ~/.bashrc

ENV GC_KERNEL_PATH=/usr/lib/habanalabs/libtpc_kernels.so
ENV HABANA_LOGS=/var/log/habana_logs/
ENV HABANA_SCAL_BIN_PATH=/opt/habanalabs/engines_fw
ENV HABANA_PLUGINS_LIB_PATH=/opt/habanalabs/habana_plugins
