version: '3.3'

services:
  hhs_level2_launcher:
    image: hhs_level2
    build:
      context: .
      network: host
      args:
        BASE_IMAGE: "${BASE_IMAGE}"
    container_name: hhs_level2_launcher
    runtime: habana
    environment:
    - HABANA_VISIBLE_DEVICES=all
    - OMPI_MCA_btl_vader_single_copy_mechanism=none
    - HHS_LEVEL=2
    cap_add:
      - SYS_NICE
    ipc: host
    network_mode: host
    working_dir: /tmp/hhs/habana_health_screen
    volumes:
      - ./ssh:/root/.ssh/
      - /tmp/hhs/habana_health_screen:/tmp/hhs/habana_health_screen
      - /etc/localtime:/etc/localtime:ro
    command: >
      template/bare-metal/run_hccl_demo.sh