# Copyright (c) 2023 HabanaLabs, Ltd.
#
# SPDX-License-Identifier: Apache-2.0
#
# HabanaLabs Dockerfile Tensorflow installer layer for RHEL 8.6

ARG BASE_NAME
ARG VERSION
ARG REVISION
FROM ${BASE_NAME}:${VERSION}-${REVISION}
ARG BASE_NAME
ARG VERSION
ARG REVISION
ARG TF_VERSION
ARG ARTIFACTORY_URL

LABEL name="Tensorflow Installer (${TF_VERSION})"
LABEL summary="Habanalabs Tensorflow (${TF_VERSION}) installer layer for RHEL 8.6"
LABEL description="Image with pre installed Habanalabs packages for Tensorflow-${TF_VERSION}"

ENV TF_MODULES_RELEASE_BUILD=/usr/lib/habanalabs/
ENV PYTHONPATH=/root:/usr/lib/habanalabs/

# Install unzip to extract pre-trained weights for BERT demo
RUN dnf install -y \
        bc \
        protobuf-devel \
        libffi-devel \
        bzip2-devel && \
    dnf clean all && rm -rf /var/cache/dnf

COPY install-python310.sh install-python310.sh
RUN ./install-python310.sh $BASE_NAME
ENV LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH

RUN python3.10 -m pip install habana_media_loader=="${VERSION}"."${REVISION}" && \
    python3.10 -m pip install tensorflow-cpu==${TF_VERSION} && \
    python3.10 -m pip install habana-tensorflow=="${VERSION}"."${REVISION}" && \
    python3.10 -m pip install habana-horovod=="${VERSION}"."${REVISION}"

# For AML/CentOS/RHEL OS'es TFIO_DATAPATH have to be specified to import tensorflow_io lib correctly
ENV TFIO_DATAPATH=/usr/local/lib64/python3.10/site-packages/

# For AML/CentOS/RHEL ca-cert file is expected exactly under /etc/ssl/certs/ca-certificates.crt
# otherwise curl will fail during access to S3 AWS storage
RUN ln -s /etc/ssl/certs/ca-bundle.crt /etc/ssl/certs/ca-certificates.crt

RUN echo "source /etc/profile.d/habanalabs.sh" >> ~/.bashrc && \
    dnf clean all && rm -rf /var/cache/dnf && rm -rf /tmp/*