# Copyright (c) 2023 HabanaLabs, Ltd.
#
# SPDX-License-Identifier: Apache-2.0
#
# HabanaLabs Dockerfile Tensorflow installer layer for debian
ARG BASE_NAME
ARG VERSION
ARG REVISION
FROM ${BASE_NAME}:${VERSION}-${REVISION}
ARG BASE_NAME
ARG VERSION
ARG REVISION
ARG TF_VERSION
ARG ARTIFACTORY_URL

ENV TF_MODULES_RELEASE_BUILD=/usr/lib/habanalabs/
ENV PYTHONPATH=/usr/lib/habanalabs/:/root
COPY install-python310.sh install-python310.sh
RUN ./install-python310.sh $BASE_NAME
ENV LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH

RUN python3 -m pip install habana_media_loader=="${VERSION}"."${REVISION}" && \
    python3 -m pip install tensorflow-cpu==${TF_VERSION} && \
    python3 -m pip install habana-tensorflow=="${VERSION}"."${REVISION}" && \
    python3 -m pip install habana-horovod=="${VERSION}"."${REVISION}"

RUN echo "source /etc/profile.d/habanalabs.sh" >> ~/.bashrc && \
    rm -rf /tmp/*