version: '3.3'

services:
  ighs_level2_worker:
    image: ighs_level2
    build:
      context: .
      network: host
      args:
        BASE_IMAGE: "${BASE_IMAGE}"
    container_name: ighs_level2_worker
    runtime: habana
    environment:
    - HABANA_VISIBLE_DEVICES=all
    - OMPI_MCA_btl_vader_single_copy_mechanism=none
    - IGHS_LEVEL=2
    cap_add:
      - SYS_NICE
    ipc: host
    network_mode: host
    working_dir: /tmp/ighs/intel_gaudi_health_screen
    volumes:
      - ./ssh:/root/.ssh/
      - /tmp/ighs/intel_gaudi_health_screen:/tmp/ighs/intel_gaudi_health_screen
      - /etc/localtime:/etc/localtime:ro
    tty: true
