# Copyright (c) 2024 HabanaLabs, Ltd.
#
# SPDX-License-Identifier: Apache-2.0
#
# HabanaLabs Dockerfile PyTorch installer layer for SUSE 15.5
ARG BASE_NAME
ARG VERSION
ARG REVISION
FROM ${BASE_NAME}:${VERSION}-${REVISION}
ARG PT_VERSION
ARG VERSION
ARG REVISION
ARG BASE_NAME
ARG ARTIFACTORY_URL

# for RHEL certification
LABEL name="PyTorch Installer"
LABEL summary="Habanalabs PyTorch installer layer for SUSE 15.5"
LABEL description="Image with pre installed Habanalabs packages for PyTorch"

ENV PYTHONPATH=/root:/usr/lib/habanalabs/

RUN zypper install -y --allow-downgrade \
    cairo-devel \
    numactl \
    lapack-devel \
    numactl \
    gperftools-devel

RUN zypper addrepo -f https://yum.repos.intel.com/oneapi oneAPI && \
    echo "gpgcheck=0" >> /etc/zypp/repos.d/oneAPI.repo && \
    echo "repo_gpgcheck=0" >> /etc/zypp/repos.d/oneAPI.repo

RUN zypper install -y intel-oneapi-mkl-2021.1.1 intel-oneapi-mkl-devel-2021.1.1


COPY install_packages.sh .

RUN ./install_packages.sh && rm -f install_packages.sh && \
    /sbin/ldconfig && echo "source /etc/profile.d/habanalabs.sh" >> ~/.bashrc

# Set LD_PRELOAD after all required installations to
# avoid warnings during docker creation
ENV LD_PRELOAD=/usr/lib64/libtcmalloc.so.4
ENV TCMALLOC_LARGE_ALLOC_REPORT_THRESHOLD=7516192768

RUN rm -rf /tmp/*