# Copyright (c) 2024 HabanaLabs, Ltd.
#
# SPDX-License-Identifier: Apache-2.0
#
# HabanaLabs Dockerfile PyTorch installer layer for SUSE 15.5
ARG BASE_NAME
ARG VERSION
ARG REVISION
FROM ${BASE_NAME}:${VERSION}-${REVISION}
ARG PT_VERSION
ARG VERSION
ARG REVISION
ARG BASE_NAME
ARG ARTIFACTORY_URL

# for RHEL certification
LABEL name="PyTorch Installer"
LABEL summary="Habanalabs PyTorch installer layer for SUSE 15.5"
LABEL description="Image with pre installed Habanalabs packages for PyTorch"

ENV PYTHONPATH=/root:/usr/lib/habanalabs/

RUN zypper update -y && zypper install -y --allow-downgrade \
        cairo-devel \
        gperftools-devel \
        jq \
        lapack-devel \
        numactl && \
    zypper clean

COPY install_packages.sh .

RUN ./install_packages.sh && rm -f install_packages.sh && \
    /sbin/ldconfig && echo "source /etc/profile.d/habanalabs.sh" >> ~/.bashrc

# Set LD_PRELOAD after all required installations to
# avoid warnings during docker creation
ENV LD_PRELOAD=/usr/lib64/libtcmalloc.so.4
ENV TCMALLOC_LARGE_ALLOC_REPORT_THRESHOLD=7516192768