# Copyright (c) 2023 HabanaLabs, Ltd.
#
# SPDX-License-Identifier: Apache-2.0
#
# HabanaLabs Dockerfile PyTorch installer layer for Debian 10
ARG BASE_NAME
ARG VERSION
ARG REVISION
FROM ${BASE_NAME}:${VERSION}-${REVISION}
ARG BASE_NAME
ARG PT_VERSION
ARG VERSION
ARG REVISION
ARG ARTIFACTORY_URL

ENV LANG=en_US.UTF-8
ENV PYTHONPATH=/root:/usr/lib/habanalabs/

RUN apt update && apt install -y \
    libgoogle-perftools-dev \
    iproute2 \
    libcairo2-dev \
    libcurl4 \
    libglib2.0-dev \
    libjpeg-dev \
    liblapack-dev \
    libnuma-dev \
    libopenblas-dev \
    libpcre2-dev \
    libselinux1-dev \
    moreutils \
    numactl && \
    apt clean

# Default python is pointing to 3.7
RUN bash -c "\
    ln -sf /usr/lib/x86_64-linux-gnu/libtcmalloc.so.4 /lib/x86_64-linux-gnu/libtcmalloc.so.4; \
"

COPY install_packages.sh .

RUN ./install_packages.sh && rm -f install_packages.sh && \
    /sbin/ldconfig && echo "source /etc/profile.d/habanalabs.sh" >> ~/.bashrc

ENV LD_PRELOAD=/lib/x86_64-linux-gnu/libtcmalloc.so.4
ENV TCMALLOC_LARGE_ALLOC_REPORT_THRESHOLD=7516192768

RUN rm -rf /tmp/*