# Copyright (c) 2024 HabanaLabs, Ltd.
#
# SPDX-License-Identifier: Apache-2.0
#
# HabanaLabs Dockerfile PyTorch installer layer for RHEL 8.6
ARG BASE_NAME
ARG VERSION
ARG REVISION
FROM ${BASE_NAME}:${VERSION}-${REVISION}
ARG PT_VERSION
ARG VERSION
ARG REVISION
ARG BASE_NAME
ARG ARTIFACTORY_URL

LABEL name="PyTorch Installer"
LABEL summary="Habanalabs PyTorch installer layer for Tencentos 3.1"
LABEL description="Image with pre installed Habanalabs packages for PyTorch"

ENV PYTHONPATH=/root:/usr/lib/habanalabs/

RUN dnf versionlock add openmpi* perftest*

RUN dnf update -y && dnf install -y \
        cairo-devel \
        curl \
        gcc-toolset-11 \
        gperftools-devel \
        iproute \
        jq \
        lapack-devel \
        numactl \
        numactl-devel \
        openblas-devel \
        libevent \
        pdsh \
        which \
        zlib-devel && \
    dnf clean all

# Configure GCC 11
ENV PATH=/opt/rh/gcc-toolset-11/root/usr/bin:${PATH}
ENV MANPATH=/opt/rh/gcc-toolset-11/root/usr/share/man:${MANPATH}
ENV INFOPATH=/opt/rh/gcc-toolset-11/root/usr/share/info:${INFOPATH}
ENV PCP_DIR=/opt/rh/gcc-toolset-11/root
ENV LD_LIBRARY_PATH=/usr/mpi/gcc/openmpi-4.1.5a1/lib64:/opt/rh/gcc-toolset-11/root/usr/lib64:/opt/rh/gcc-toolset-11/root/usr/lib:/opt/rh/gcc-toolset-11/root/usr/lib64/dyninst:/opt/rh/gcc-toolset-11/root/usr/lib/dyninst:${LD_LIBRARY_PATH}
ENV PKG_CONFIG_PATH=/opt/rh/gcc-toolset-11/root/usr/lib64/pkgconfig:/usr/mpi/gcc/openmpi-4.1.5a1/lib64/pkgconfig:${PKG_CONFIG_PATH}
ENV CMAKE_PREFIX_PATH=/usr/mpi/gcc/openmpi-4.1.5a1/include:${CMAKE_PREFIX_PATH}

COPY install_packages.sh .

RUN ./install_packages.sh && rm -f install_packages.sh && \
    /sbin/ldconfig && echo "source /etc/profile.d/habanalabs.sh" >> ~/.bashrc

ENV LD_PRELOAD=/lib64/libtcmalloc.so.4
ENV TCMALLOC_LARGE_ALLOC_REPORT_THRESHOLD=7516192768
