# Copyright (c) 2025 HabanaLabs, Ltd.
#
# SPDX-License-Identifier: Apache-2.0
#
# HabanaLabs Dockerfile PyTorch installer layer for RHEL 9.6
ARG BASE_NAME
ARG VERSION
ARG REVISION
FROM ${BASE_NAME}:${VERSION}-${REVISION}
ARG PT_VERSION
ARG VERSION
ARG REVISION
ARG BASE_NAME
ARG ARTIFACTORY_URL
ARG TORCH_TYPE

LABEL name="PyTorch Installer for OpenShift Workbenches"
LABEL summary="Habanalabs PyTorch installer layer for RHEL9.6 dedicated for OpenShift Workbenches"
LABEL description="Image with pre installed Habanalabs packages for PyTorch dedicated for OpenShift Workbenches"

RUN echo "/usr/lib/habanalabs" > $(python3 -c "import sysconfig; print(sysconfig.get_path('platlib'))")/habanalabs-graph.pth

USER 0

RUN dnf install --nodocs --setopt=install_weak_deps=false --allowerasing -y \
        cairo-devel \
        gperftools-devel \
        jq \
        lapack-devel \
        numactl \
        numactl-devel \
        openblas-devel \
        which && \
    dnf clean all

COPY install_packages.sh .
RUN ./install_packages.sh && rm -f install_packages.sh && \
    /sbin/ldconfig

USER 1001
RUN echo "source /etc/profile.d/habanalabs.sh" >> ~/.bashrc

# Set LD_PRELOAD after all required installations to
# avoid warnings during docker creation
ENV LD_PRELOAD=/usr/lib64/libtcmalloc.so.4
ENV TCMALLOC_LARGE_ALLOC_REPORT_THRESHOLD=7516192768
WORKDIR /opt/app-root/src
