# Copyright (c) 2025 HabanaLabs, Ltd.
#
# SPDX-License-Identifier: Apache-2.0
#
# HabanaLabs Dockerfile PyTorch installer layer for OpenCloudOS 9.2
ARG BASE_NAME
ARG VERSION
ARG REVISION
FROM ${BASE_NAME}:${VERSION}-${REVISION}
ARG PT_VERSION
ARG VERSION
ARG REVISION
ARG BASE_NAME
ARG ARTIFACTORY_URL
ARG TORCH_TYPE

LABEL name="PyTorch Installer"
LABEL summary="Habanalabs PyTorch installer layer for OpenCloudOS 9.2"
LABEL description="Image with pre installed Habanalabs packages for PyTorch"

ENV PYTHONPATH=/root:/usr/lib/habanalabs/

RUN dnf update --nobest -y && dnf install --nobest --allowerasing -y \
        cairo-devel \
        curl \
        gperftools-devel \
        iproute \
        jq \
        lapack-devel \
        numactl \
        numactl-devel \
        openblas-devel \
        which \
        zlib-devel && \
    dnf clean all

COPY install_packages.sh .

RUN ./install_packages.sh && rm -f install_packages.sh && \
    /sbin/ldconfig && echo "source /etc/profile.d/habanalabs.sh" >> ~/.bashrc

# Set LD_PRELOAD after all required installations to
# avoid warnings during docker creation
ENV LD_PRELOAD=/usr/lib64/libtcmalloc.so.4
ENV TCMALLOC_LARGE_ALLOC_REPORT_THRESHOLD=7516192768

RUN rm -f /etc/yum.repos.d/habana.repo