# Copyright (c) 2023 HabanaLabs, Ltd.
#
# SPDX-License-Identifier: Apache-2.0
#
# HabanaLabs Dockerfile PyTorch installer layer for Ubuntu18.04/Ubuntu20.04/Ubuntu22.04
ARG BASE_NAME
ARG VERSION
ARG REVISION
FROM ${BASE_NAME}:${VERSION}-${REVISION}
ARG PT_VERSION
ARG VERSION
ARG REVISION
ARG BASE_NAME
ARG ARTIFACTORY_URL
ARG HABANA_PIP_VERSION="22.3"

ENV LANG=en_US.UTF-8
ENV PYTHONPATH=/root:/usr/lib/habanalabs/

RUN apt-get update && apt-get install -y \
    unzip \
    curl \
    libcurl4 \
    moreutils \
    iproute2 \
    libcairo2-dev \
    libglib2.0-dev \
    libhdf5-dev \
    libselinux1-dev \
    libnuma-dev \
    libpcre2-dev \
    libjpeg-dev \
    liblapack-dev \
    libopenblas-dev \
    numactl \
    libgoogle-perftools-dev && \
    apt-get clean

RUN bash -c "\
    case $BASE_NAME in \
            *ubuntu18.04*) \
                rm -rf /usr/bin/python /usr/bin/python3m; \
                ln -s /usr/bin/python3.8 /usr/bin/python; \
                ln -s /usr/bin/python3.8m /usr/bin/python3m; \
                ln -sf /usr/lib/x86_64-linux-gnu/libtcmalloc.so.4 /lib/x86_64-linux-gnu/libtcmalloc.so.4; \
            ;; \
            *ubuntu20.04*) \
                ln -s /usr/bin/python3.8 /usr/bin/python; \
            ;; \
            *ubuntu22.04*) \
               ln -s /usr/bin/python3.10 /usr/bin/python; \
            ;; \
        esac"

RUN wget https://"${ARTIFACTORY_URL}"/artifactory/gaudi-pt-modules/"${VERSION}"/"${REVISION}"\
/pytorch/ubuntu${OS_NUMBER}/pytorch_modules-v"${PT_VERSION}"_"${VERSION}"_"${REVISION}".tgz && \
    mkdir -p /root/habanalabs/pytorch_temp && \
    tar -xf pytorch_modules-v"${PT_VERSION}"_"${VERSION}"_"${REVISION}".tgz -C /root/habanalabs/pytorch_temp/. && \
    python3 -m pip install pip=="${HABANA_PIP_VERSION}" && \
    pip install mpi4py==3.1.4 && \
    pip install -r /root/habanalabs/pytorch_temp/requirements-pytorch.txt --no-warn-script-location && \
    pip install /root/habanalabs/pytorch_temp/torchvision*.whl && \
    pip uninstall --yes torch && \
    rm -rf /root/habanalabs/pytorch_temp/torchvision*.whl && \
    pip install /root/habanalabs/pytorch_temp/*.whl && \
    /sbin/ldconfig && \
    echo "source /etc/profile.d/habanalabs.sh" >> ~/.bashrc && \
    pip uninstall -y pillow && \
    pip uninstall -y pillow-simd && \
    pip install pillow-simd==7.0.0.post3 && \
    rm -rf /root/habanalabs/pytorch_temp/ && \
    rm -rf pytorch_modules-v"${PT_VERSION}"_"${VERSION}"_"${REVISION}".tgz
# requirement-pytorch.txt installs a pkg called torchvision.torchvision has dependency on "torch" pkg
# pytorch uses its own package "torch", to avoid the conflict between two pkgs, we uninstall torch pkg installed by torchvision

ENV LD_PRELOAD=/lib/x86_64-linux-gnu/libtcmalloc.so.4
ENV TCMALLOC_LARGE_ALLOC_REPORT_THRESHOLD=7516192768

RUN rm -rf /tmp/*