# Copyright (c) 2022 HabanaLabs, Ltd.
#
# SPDX-License-Identifier: Apache-2.0
#
# HabanaLabs Dockerfile Tensorflow installer layer for Ubuntu18.04/Ubuntu20.04
ARG BASE_NAME
ARG VERSION
ARG REVISION
FROM ${BASE_NAME}:${VERSION}-${REVISION}
ARG VERSION
ARG REVISION
ARG TF_VERSION
ARG ARTIFACTORY_URL

ENV TF_MODULES_RELEASE_BUILD=/usr/lib/habanalabs/
ENV PYTHONPATH=/usr/lib/habanalabs/:/root

COPY requirements-no-deps-tensorflow-cpu-"$TF_VERSION".txt requirements-no-deps-tensorflow-cpu-"$TF_VERSION".txt

RUN python3 -m pip install pip==21.0.1 && \
    pip3 install setuptools==60.5.0 && \
    pip3 install --use-pep517 tensorflow-cpu==${TF_VERSION} \
        tensorflow-model-optimization==0.7.0 && \
    pip3 install --no-deps -r requirements-no-deps-tensorflow-cpu-"$TF_VERSION".txt && \
    rm requirements-no-deps-tensorflow-cpu-"$TF_VERSION".txt

RUN python3 -m pip install habana-tensorflow=="${VERSION}"."${REVISION}" && \
    python3 -m pip install habana-horovod=="${VERSION}"."${REVISION}" && \
    echo "source /etc/profile.d/habanalabs.sh" >> ~/.bashrc && \
    echo "/etc/init.d/ssh start \"-p 3022\"" >> ~/.bashrc

RUN rm -rf /tmp/*