# Copyright (c) 2021 HabanaLabs, Ltd.
#
# SPDX-License-Identifier: Apache-2.0
#
# HabanaLabs Dockerfile PyTorch installer layer for Amazon Linux 2
ARG BASE_NAME
ARG VERSION
ARG REVISION
FROM ${BASE_NAME}:${VERSION}-${REVISION}
ARG VERSION
ARG REVISION
ARG ARTIFACTORY_URL
ARG OPENMPI_VER=4.0.5

ENV LANG=en_US.UTF-8

RUN yum install -y \
    unzip \
    openssh-clients \
    openssh-server \
    curl \
    redhat-lsb-core \
    openmpi-devel \
    lsof \
    cairo-devel \
    iproute \
    git \
    which \
    libjpeg-devel \
    zlib-devel && \
    yum clean all

RUN amazon-linux-extras install epel -y
RUN yum install -y \
    moreutils && \
    yum clean all

RUN wget https://bootstrap.pypa.io/get-pip.py && \
    python3 get-pip.py pip==21.0.1 --no-warn-script-location && \
    rm -rf get-pip.py

RUN wget --no-verbose https://download.open-mpi.org/release/open-mpi/v4.0/openmpi-"${OPENMPI_VER}".tar.gz && \
    tar -xvf openmpi-"${OPENMPI_VER}".tar.gz && \
    cd openmpi-"${OPENMPI_VER}" && \
    ./configure --prefix="/usr/lib/habanalabs/openmpi" && \
    make -j && \
    make install && \
    cp LICENSE /usr/lib/habanalabs/openmpi && \
    cd - && \
    rm -rf openmpi-"${OPENMPI_VER}"* && \
    /sbin/ldconfig

ENV MPI_ROOT=/usr/lib/habanalabs/openmpi
ENV PATH=$MPI_ROOT/bin:$PATH

RUN MPICC=/usr/lib/habanalabs/openmpi/bin/mpicc pip3 install mpi4py==3.0.3 --no-cache-dir

RUN wget "https://${ARTIFACTORY_URL}"/gaudi-pt-modules/"${VERSION}"/"${REVISION}"\
/amzn2/binary/pytorch_modules-"${VERSION}"_"${REVISION}".tgz && \
    mkdir /root/habanalabs /root/habanalabs/pytorch_temp && \
    tar -xf pytorch_modules-"${VERSION}"_"${REVISION}".tgz -C /root/habanalabs/pytorch_temp/. && \
    mv /root/habanalabs/pytorch_temp/*.so /usr/lib/habanalabs/ && \
    pip3 install -r /root/habanalabs/pytorch_temp/requirements-pytorch.txt --user --no-warn-script-location && \
    pip3 uninstall --yes torch && \
    pip3 install /root/habanalabs/pytorch_temp/*.whl --user && \
    /sbin/ldconfig && \
    echo "source /etc/profile.d/habanalabs.sh" >> ~/.bashrc && \
    pip3 uninstall -y pillow && \
    pip3 uninstall -y pillow-simd && \
    pip3 install pillow-simd==7.0.0.post3 --user && \
    rm -rf /root/habanalabs/pytorch_temp/ && \
    rm -rf pytorch_modules-"${VERSION}"_"${REVISION}".tgz

ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/root/.local/lib:/usr/lib/habanalabs/