# Copyright (c) 2022 HabanaLabs, Ltd.
#
# SPDX-License-Identifier: Apache-2.0
#
# HabanaLabs Dockerfile PyTorch installer layer for Amazon Linux 2
ARG BASE_NAME
ARG VERSION
ARG REVISION
FROM ${BASE_NAME}:${VERSION}-${REVISION}
ARG PT_VERSION
ARG VERSION
ARG REVISION
ARG ARTIFACTORY_URL

ENV LANG=en_US.UTF-8

RUN yum install -y \
    unzip \
    curl \
    redhat-lsb-core \
    numactl-devel \
    cairo-devel \
    iproute \
    git \
    which \
    libjpeg-devel \
    zlib-devel \
    lapack-devel \
    blas-devel \
    numactl && \
    yum clean all

RUN amazon-linux-extras install epel -y
RUN yum install -y \
    moreutils && \
    yum clean all

RUN wget https://bootstrap.pypa.io/get-pip.py && \
    python3 get-pip.py pip==21.0.1 --no-warn-script-location && \
    rm -rf get-pip.py && \
    pip3 install mpi4py==3.0.3 --no-cache-dir

RUN wget "https://${ARTIFACTORY_URL}"/artifactory/gaudi-pt-modules/"${VERSION}"/"${REVISION}"\
/amzn2/binary/pytorch_modules-v"${PT_VERSION}"_"${VERSION}"_"${REVISION}".tgz && \
    mkdir /root/habanalabs /root/habanalabs/pytorch_temp && \
    tar -xf pytorch_modules-v"${PT_VERSION}"_"${VERSION}"_"${REVISION}".tgz -C /root/habanalabs/pytorch_temp/. && \
    pip3 install -r /root/habanalabs/pytorch_temp/requirements-pytorch.txt --no-warn-script-location && \
    pip3 install /root/habanalabs/pytorch_temp/torchvision*.whl && \
    pip3 uninstall --yes torch && \
    rm -rf /root/habanalabs/pytorch_temp/torchvision*.whl && \
    pip3 install /root/habanalabs/pytorch_temp/*.whl && \
    /sbin/ldconfig && \
    echo "source /etc/profile.d/habanalabs.sh" >> ~/.bashrc && \
    pip3 uninstall -y pillow && \
    pip3 uninstall -y pillow-simd && \
    pip3 install pillow-simd==7.0.0.post3 && \
    rm -rf /root/habanalabs/pytorch_temp/ && \
    rm -rf pytorch_modules-v"${PT_VERSION}"_"${VERSION}"_"${REVISION}".tgz

RUN rm -rf /tmp/*