# Copyright (c) 2022 HabanaLabs, Ltd.
#
# SPDX-License-Identifier: Apache-2.0
#
# HabanaLabs Dockerfile Tensorflow installer layer for debian
ARG BASE_NAME
ARG VERSION
ARG REVISION
FROM ${BASE_NAME}:${VERSION}-${REVISION}
ARG VERSION
ARG REVISION
ARG TF_VERSION
ARG ARTIFACTORY_URL

ENV TF_MODULES_RELEASE_BUILD=/usr/lib/habanalabs/
ENV PYTHONPATH=/usr/lib/habanalabs/:/root

COPY requirements-tensorflow-cpu-"$TF_VERSION".txt requirements-tensorflow-cpu-"$TF_VERSION".txt

RUN python3 -m pip install pip==21.0.1 \
    setuptools==60.5.0 && \
    python3 -m pip install tensorflow-cpu==${TF_VERSION} && \
    python3 -m pip install -r requirements-tensorflow-cpu-"$TF_VERSION".txt && \
    rm requirements-tensorflow-cpu-"$TF_VERSION".txt && \
    python3 -m pip install habana-tensorflow=="${VERSION}"."${REVISION}" && \
    python3 -m pip install habana-horovod=="${VERSION}"."${REVISION}"

RUN echo "source /etc/profile.d/habanalabs.sh" >> ~/.bashrc && \
    rm -rf /tmp/*
