# Copyright (c) 2021 HabanaLabs, Ltd.
#
# SPDX-License-Identifier: Apache-2.0
#
# HabanaLabs Dockerfile base installer layer for Ubuntu 18.04
FROM ubuntu:bionic
ARG ARTIFACTORY_URL
ARG VERSION
ARG REVISION
ARG HABANA_PIP_VERSION="19.3.1"

ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8
ENV LC_CTYPE=en_US.UTF-8
ENV DEBIAN_FRONTEND=noninteractive
ENV GC_KERNEL_PATH=/usr/lib/habanalabs/libtpc_kernels.so
ENV HABANA_LOGS=/var/log/habana_logs/
ENV OS_NUMBER=1804

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    apt-transport-https \
    apt-utils \
    ethtool \
    gpg-agent \
    libjemalloc1 \
    software-properties-common \
    wget && \
    apt-get autoremove && apt-get clean

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    ca-certificates \
    dkms \
    gcc \
    graphviz \
    libgoogle-glog0v5 \
    libopencv-dev \
    libpq-dev \
    locales \
    make \
    protobuf-compiler && \
    apt-get autoremove && apt-get clean

RUN apt-get update && \
    ### Install ssh for horovod/MPI
    apt-get install -y --no-install-recommends \
    bc \
    git \
    openssh-client \
    openssh-server \
    unzip \
    vim \
    lsof \
    python3-pip && \
    apt-get autoremove && apt-get clean

RUN locale-gen en_US.UTF-8

# Update default Python to 3.7 as Habana dropped support for python older than 3.7
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        python3.7 \
        python3.7-dev \
        python3.7-venv \
        # there is no dedicated package distutils, tk for python 3.7
        python3-distutils \
        python3-tk && \
    apt-get autoremove --yes && apt-get clean && rm -rf /var/lib/apt/lists/* && \
        update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 10 && \
        update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 1 && \
        update-alternatives --install /usr/bin/python python /usr/bin/python3.7 10 && \
        update-alternatives --install /usr/bin/python python /usr/bin/python3.6 1

RUN python3 -m pip install --no-cache-dir pip=="${HABANA_PIP_VERSION}" && \
    # There is no need to store pip installation files inside docker image
    pip3 config set global.no-cache-dir false && \
    pip3 install setuptools==41.0.0

# Required symlinks for fix cannot import modues _gi, apt_pkg after python 3.7 installation in add-apt-repository script
RUN ln -s /usr/lib/python3/dist-packages/apt_pkg.cpython-36m-x86_64-linux-gnu.so /usr/lib/python3/dist-packages/apt_pkg.so && \
    ln -s /usr/lib/python3/dist-packages/gi/_gi.cpython-36m-x86_64-linux-gnu.so /usr/lib/python3/dist-packages/gi/_gi.cpython-37m-x86_64-linux-gnu.so

RUN yes '' | add-apt-repository ppa:deadsnakes/ppa && \
    echo "deb https://${ARTIFACTORY_URL}/artifactory/debian bionic main" | tee -a /etc/apt/sources.list && \
    wget "https://${ARTIFACTORY_URL}/artifactory/api/gpg/key/public" && \
    apt-key add public && rm public

RUN apt-get update && \
    apt-get install -y habanalabs-thunk="$VERSION"-"$REVISION" \
        habanalabs-firmware-tools="$VERSION"-"$REVISION" \
        habanalabs-graph="$VERSION"-"$REVISION" && \
        apt-get autoremove --yes && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN sed --in-place "/$ARTIFACTORY_URL/d" /etc/apt/sources.list