# Copyright (c) 2021 HabanaLabs, Ltd.
#
# SPDX-License-Identifier: Apache-2.0
#
# HabanaLabs Dockerfile base installer layer for Ubuntu 18.04
FROM ubuntu:bionic-20210512
ARG ARTIFACTORY_URL
ARG VERSION
ARG REVISION

ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8
ENV LC_CTYPE=en_US.UTF-8
ENV DEBIAN_FRONTEND=noninteractive
ENV GC_KERNEL_PATH=/usr/lib/habanalabs/libtpc_kernels.so
ENV HABANA_LOGS=/var/log/habana_logs/
ENV OS_NUMBER=1804

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    apt-transport-https=1.6.13 \
    apt-utils=1.6.13 \
    ethtool=1:4.15-0ubuntu1 \
    gpg-agent=2.2.4-1ubuntu1.4 \
    libjemalloc1=3.6.0-11 \
    software-properties-common=0.96.24.32.14 \
    wget=1.19.4-1ubuntu2.2 && \
    apt-get autoremove && apt-get clean

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential=12.4ubuntu1 \
    ca-certificates=20210119~18.04.1 \
    dkms=2.3-3ubuntu9.7 \
    gcc=4:7.4.0-1ubuntu2.3 \
    graphviz=2.40.1-2 \
    libgoogle-glog0v5=0.3.5-1 \
    libopencv-dev=3.2.0+dfsg-4ubuntu0.1 \
    libpq-dev=10.17-0ubuntu0.18.04.1 \
    locales=2.27-3ubuntu1.4 \
    make=4.1-9.1ubuntu1 \
    protobuf-compiler=3.0.0-9.1ubuntu1 && \
    apt-get autoremove && apt-get clean

RUN apt-get update && \
    ### Install ssh for horovod/MPI
    apt-get install -y --no-install-recommends \
    bc=1.07.1-2 \
    git=1:2.17.1-1ubuntu0.8 \
    openssh-client=1:7.6p1-4ubuntu0.3 \
    openssh-server=1:7.6p1-4ubuntu0.3 \
    unzip=6.0-21ubuntu1.1 \
    vim=2:8.0.1453-1ubuntu1.4 && \
    apt-get autoremove && apt-get clean

RUN locale-gen en_US.UTF-8
# Install python 3.7 as default version
RUN apt-get update && \
    # Install python 3.7 packages
    apt-get install -y --no-install-recommends \
        python3.7=3.7.5-2~18.04.* \
        python3.7-dev=3.7.5-2~18.04.* \
        python3.7-venv=3.7.5-2~18.04.* \
        # there is no dedicated package distutils, tk for python 3.7
        python3-distutils=3.6.9-1~18.04 \
        python3-tk=3.6.9-1~18.04 && \
    apt-get autoremove --yes && apt-get clean && rm -rf /var/lib/apt/lists/* && \
    # Configure alternatives
        update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 10 && \
        update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 1 && \
        update-alternatives --install /usr/bin/python python /usr/bin/python3.7 10 && \
        update-alternatives --install /usr/bin/python python /usr/bin/python3.6 1 && \
    # Install pip package manager and setup tools
        wget -q https://bootstrap.pypa.io/get-pip.py && \
        python3 get-pip.py pip==19.3.1 && \
        rm get-pip.py && \
        pip3 install setuptools==41.0.0

# Required symlinks for fix cannot import modues _gi, apt_pkg after python 3.7 installation in add-apt-repository script
RUN ln -s /usr/lib/python3/dist-packages/apt_pkg.cpython-36m-x86_64-linux-gnu.so /usr/lib/python3/dist-packages/apt_pkg.so && \
    ln -s /usr/lib/python3/dist-packages/gi/_gi.cpython-36m-x86_64-linux-gnu.so /usr/lib/python3/dist-packages/gi/_gi.cpython-37m-x86_64-linux-gnu.so

RUN yes '' | add-apt-repository ppa:deadsnakes/ppa && \
    echo "deb https://${ARTIFACTORY_URL}/debian bionic main" | tee -a /etc/apt/sources.list && \
    wget "https://${ARTIFACTORY_URL}/api/gpg/key/public" && \
    apt-key add public && rm public

RUN apt-get update && \
    apt-get install -y habanalabs-thunk="$VERSION"-"$REVISION" \
        habanalabs-firmware-tools="$VERSION"-"$REVISION" \
        habanalabs-graph="$VERSION"-"$REVISION" && \
        apt-get autoremove --yes && apt-get clean && rm -rf /var/lib/apt/lists/*